config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'
  get 'courses/index'
  get 'cohorts/index'
  get 'admins/index'
  get 'students/index'
  get 'class/index'
  get 'cohort/index'
  get 'student/index'
  get 'teacher/index'
  get 'teacher_cohorts/index'
  get 'teacher_cohorts/show'
  get 'teacher_cohorts/new'
  get 'teacher_cohorts/edit'
  get 'teacher_cohorts/create'
  get 'teacher_cohorts/update'
  get 'teacher_cohorts/delete'
  get 'student_cohorts/index'
  get 'student_cohorts/show'
  get 'student_cohorts/new'
  get 'student_cohorts/edit'
  get 'student_cohorts/create'
  get 'student_cohorts/update'
  get 'student_cohorts/delete'
  resources :users
  resources :admins
  resources :cohorts
  resources :courses
  resources :teachers
  resources :students
  get 'welcome/index'
 
  root 'welcome#index'
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
has_many :teacher_cohorts
has_many :teachers, through: :teacher_cohorts
has_many :student_cohorts
has_many :students, through: :student_cohorts
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: %i[show edit update destroy]

  def index
    @cohorts = Cohort.all
  end

  def show; end

  def new
    @cohort = Cohort.new
  end

  def edit; end

  def create
    @cohort = Cohort.new(cohort_params)

    respond_to do |format|
      if @cohort.save
        format.html { redirect_to @cohort, notice: 'Successfully created Cohort.' }
        format.json { render :show, status: :created, location: @cohort }
      else
        format.html { render :new }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cohort.update(cohort_params)
        format.html { redirect_to @cohort, notice: 'Successfully updated Cohort.' }
        format.json { render :show, status: :ok, location: @cohort }
      else
        format.html { render :edit }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cohort.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_url, notice: 'Successfully destroyed Cohort.' }
      format.json { head :no_content }
    end
  end

  private

  def set_cohort
    @cohort = Cohort.find(params[:id])
  end

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :course_id)
  end
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_form.html.erb
<%= form_with(model: cohort, local: true) do |form| %>
  <% if cohort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cohort.errors.count, "error") %> prohibited this cohort from being saved:</h2>

      <ul>
      <% cohort.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div>
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div>
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cohorts/edit.html.erb
<div class="container">

  <header class="header">

    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>

  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
      
        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

      </ul>
    </nav>

    <main class="main-view">

      <div class="overview">

        <h1 class="overview_heading"> Cohorts </h1>

        <% if notice != nil %>
          <div class="overview_rating" id="notice">
            <div class="overview_rating-average">
              <%= notice %>
            </div>  
          </div>
        <% end %>

      </div>

      <div class="detail">

        <div class="description">

          <h1>Editing Cohort</h1>

          <%= render 'form', cohort: @cohort %>
          <%= link_to 'Show', @cohort %> |
          <%= link_to 'Back', cohorts_path %>

        </div>
    </main>
</div>

app/views/cohorts/index.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
    
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Courses
        </h1>

        <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
          <p class="paragraph">

        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Start date</th>
              <th>End date</th>
              <th>Course</th>
              <th colspan="3"><%= link_to 'New Cohort', new_cohort_path, class:" test" %>

              </th>
            </tr>
          </thead>

          <tbody>
          <% @cohorts.each do |cohort| %>
          <tr>
          <td><%= cohort.name %></td>
          <td><%= cohort.start_date %></td>
          <td><%= cohort.end_date %></td>
          <td><%= cohort.course_id %></td>
          <td><%= link_to 'Show', cohort %></td>
          <td><%= link_to 'Edit',edit_cohort_path(cohort) %></td>
          <td><%= link_to 'Destroy',cohort, method: :delete,data: {       confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
          </tbody>
        </table><br>

      <br>

    </div>
  </main>
</div>

app/views/cohorts/new.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>

  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
      
        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>
    </nav>

    <main class="main-view">

      <div class="overview">

        <h1 class="overview_heading">Cohorts</h1>

        <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>
        
      </div>

      <div class="detail">
        <div class="description">

        <h1>New Cohort</h1>

        <%= render 'form', cohort: @cohort %>
        <%= link_to 'Back', cohorts_path %>

        </div>
      </div>
    </main>
  </div>
</div>

app/views/cohorts/show.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
      
        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Cohorts
        </h1>

      <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">

<p>
  <strong>Name:</strong>
  <%= @cohort.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @cohort.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @cohort.end_date %>
</p>

<p>
  <strong>Course:</strong>
  <%= @cohort.course_id %>
</p>

<%= link_to 'Edit', edit_cohort_path(@cohort) %> |
<%= link_to 'Back', cohorts_path %>



        </div>


    </main>
    </div>