config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'
  get 'courses/index'
  get 'cohorts/index'
  get 'admins/index'
  get 'students/index'
  get 'class/index'
  get 'cohort/index'
  get 'student/index'
  get 'teacher/index'
  get 'teacher_cohorts/index'
  get 'teacher_cohorts/show'
  get 'teacher_cohorts/new'
  get 'teacher_cohorts/edit'
  get 'teacher_cohorts/create'
  get 'teacher_cohorts/update'
  get 'teacher_cohorts/delete'
  get 'student_cohorts/index'
  get 'student_cohorts/show'
  get 'student_cohorts/new'
  get 'student_cohorts/edit'
  get 'student_cohorts/create'
  get 'student_cohorts/update'
  get 'student_cohorts/delete'
  resources :users
  resources :admins
  resources :cohorts
  resources :courses
  resources :teachers
  resources :students
  get 'welcome/index'
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
has_many :teacher_cohorts
has_many :teachers, through: :teacher_cohorts
has_many :student_cohorts
has_many :students, through: :student_cohorts
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :cohorts
    has_many :students, through: :cohorts
end

app/models/post.rb
# frozen_string_literal: true

class Post < ActiveRecord::Base
  validates :title,
            presence: true,
            length: { minimum: 3, maximum: 20 },
            uniqueness: true

  validates :content,
            presence: true,
            length: { minimum: 3, maximum: 20 }
  
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :courses,
    through: :cohorts
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :courses,
    through: :cohorts
    has_many :teacher_cohorts
    has_many :cohorts, through: :teacher_cohorts
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: %i[show edit update destroy]

  def index
    @admins = Admin.all
  end

  def show; end

  def new
    @admin = Admin.new
  end

  def edit; end

  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Successfully created administrator.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Successfully updated administrator.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Successfully destroyed administrator.' }
      format.json { head :no_content }
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:username, :password)
  end
end

app/controllers/posts_contoller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Successfully created a new post.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Successfully updated the post.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Successfully destroyed post.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name, :hours)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_helper.rb
module ClassHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.username %></td>
        <td><%= admin.password %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @admin.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://i.icomoon.io/public/temp/65edbe40e8/UntitledProject/style.css">
  </head>

  <body>
    

</p>
    <%= yield %>

  </body>
</html>