config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'
  get 'courses/index'
  get 'cohorts/index'
  get 'admins/index'
  get 'students/index'
  get 'class/index'
  get 'cohort/index'
  get 'student/index'
  get 'teacher/index'
  get 'teacher_cohorts/index'
  get 'teacher_cohorts/show'
  get 'teacher_cohorts/new'
  get 'teacher_cohorts/edit'
  get 'teacher_cohorts/create'
  get 'teacher_cohorts/update'
  get 'teacher_cohorts/delete'
  get 'student_cohorts/index'
  get 'student_cohorts/show'
  get 'student_cohorts/new'
  get 'student_cohorts/edit'
  get 'student_cohorts/create'
  get 'student_cohorts/update'
  get 'student_cohorts/delete'
  resources :users
  resources :admins
  resources :cohorts
  resources :courses
  resources :teachers
  resources :students
  get 'welcome/index'
 
  root 'welcome#index'
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :courses,
    through: :cohorts
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Successfully created student.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Successfully updated student.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Successfully destroyed student.' }
      format.json { head :no_content }
    end
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name, :age, :education)
    end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :education %>
    <%= form.text_field :education %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
      
         <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Students
        </h1>
            
      <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
         <p class="paragraph">

        <h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>



          <br>
      </div>
    </main>
  </div>

app/views/students/index.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
      
         <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Students
        </h1>
            
      <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
       



<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Education</th>
      <th colspan="3">
            <%= link_to 'New Student', new_student_path, class:"test"%>
            
            </th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.age %></td>
        <td><%= student.education %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>





        </div>


    </main>
    </div>

app/views/students/new.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
      
         <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Students
        </h1>
            
      <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
         <p class="paragraph">

       <h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>
          


          <br>
      </div>
    </main>
  </div>

app/views/students/show.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
      
         <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Students
        </h1>
            
      <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
         <p class="paragraph">



<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Education:</strong>
  <%= @student.education %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>



          <br>
      </div>
    </main>
  </div>