config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'
  get 'courses/index'
  get 'cohorts/index'
  get 'admins/index'
  get 'students/index'
  get 'class/index'
  get 'cohort/index'
  get 'student/index'
  get 'teacher/index'
  get 'teacher_cohorts/index'
  get 'teacher_cohorts/show'
  get 'teacher_cohorts/new'
  get 'teacher_cohorts/edit'
  get 'teacher_cohorts/create'
  get 'teacher_cohorts/update'
  get 'teacher_cohorts/delete'
  get 'student_cohorts/index'
  get 'student_cohorts/show'
  get 'student_cohorts/new'
  get 'student_cohorts/edit'
  get 'student_cohorts/create'
  get 'student_cohorts/update'
  get 'student_cohorts/delete'
  resources :users
  resources :admins
  resources :cohorts
  resources :courses
  resources :teachers
  resources :students
  get 'welcome/index'
 
  root 'welcome#index'
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :courses,
    through: :cohorts
    has_many :teacher_cohorts
    has_many :cohorts, through: :teacher_cohorts
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = Teacher.all
  end

  def show
  end

  def new
    @teacher = Teacher.new
  end


  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Successfully added new Teacher.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Successfully updated Teacher.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Successfully destroyed Teacher.' }
      format.json { head :no_content }
    end
  end

  private

    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name, :age, :salary, :education)
    end
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div>
    <%= form.label :education %>
    <%= form.text_field :education %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
       <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Teachers 
        </h1>

        
 <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
          <p class="paragraph">
            
             <h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

          </p>

        </div>



    </main>
    </div>
  </div>

app/views/teachers/index.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
          <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Teachers
        </h1>

        <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>
      </div>

      <div class="detail">
        <div class="description">
          <p class="paragraph">
         
        

            <table>
              <thead>
                <tr>
                  <th>First name</th>
                  <th>Last name</th>
                  <th>Age</th>
                  <th>Salary</th>
                  <th>Education</th>
                  <th colspan="3" >
            <%= link_to 'New Teacher', new_teacher_path,class:"test"%>
            </th>
                </tr>
              </thead>

              <tbody>
                <% @teachers.each do |teacher| %>
                  <tr>
                    <td>
                      <%= teacher.first_name %>
                    </td>
                    <td>
                      <%= teacher.last_name %>
                    </td>
                    <td>
                      <%= teacher.age %>
                    </td>
                    <td>
                      <%= teacher.salary %>
                    </td>
                    <td>
                      <%= teacher.education %>
                    </td>
                    <td>
                      <%= link_to 'Show', teacher %>
                    </td>
                    <td>
                      <%= link_to 'Edit', edit_teacher_path(teacher) %>
                    </td>
                    <td>
                      <%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
                  <% end %>
              </tbody>
            </table>

            <br>
           
          </p>

        </div>


    </main>
    </div>
  </div>

app/views/teachers/new.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
       <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Teachers 
        </h1>

        
      <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
          <p class="paragraph">
            
             <h1>New Teacher</h1>

              <%= render 'form', teacher: @teacher %>

              <%= link_to 'Back', teachers_path %>
          </p>

        </div>


    </main>
    </div>
  </div>

app/views/teachers/show.html.erb
<div class="container">
  <header class="header">
    <H1 class='school-title'>NYCDA</h1>

    <nav class="main-nav">
      <div>
        <a href="/">Sign In</a>
      </div>
      <div>
        <a href="/">Sign Up</a>
      </div>
    </nav>
  </header>


  <div class="content">
    <nav class="sidebar">
      <ul class="side-nav">
          <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("home.svg", class:'side-nav_icon')  %>
            <span></span>
          </a>
        </li>

        <li class="side-nav_item side-nav_item--active">
          <a href="/teachers" class="side-nav_link">
            <%= image_tag("people.svg", class:'side-nav_icon') %> 
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/students" class="side-nav_link">
            <%= image_tag("student.svg",class:'side-nav_icon')   %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/cohorts" class="side-nav_link">
            <%= image_tag("cohort.svg",class:'side-nav_icon') %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/courses" class="side-nav_link">
            <%= image_tag("course.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>

        <li class="side-nav_item">
          <a href="/" class="side-nav_link">
            <%= image_tag("settings.svg", class:'side-nav_icon')  %>
              <span></span>
          </a>
        </li>
      </ul>


    </nav>



    <main class="main-view">

      <div class="overview">
        <h1 class="overview_heading">
          Teachers 
        </h1>

       <% if notice != nil %>
        <div class="overview_rating" id="notice">
          <div class="overview_rating-average">
            <%= notice %>
          </div>  
        </div>
        <% end %>

      </div>


      <div class="detail">
        <div class="description">
          <p class="paragraph">
          

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @teacher.age %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @teacher.salary %>
</p>

<p>
  <strong>Education:</strong>
  <%= @teacher.education %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

        </div>


    </main>
    </div>
  </div>